# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: radix-cost-allocation-api
  namespace: radix-cost-allocation-api-dev
  env: dev

component:
  name: server
  pipelineImage: release-latest
  port: 3003