// Code generated by MockGen. DO NOT EDIT.
// Source: ./models/radix_api/client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	radix_api "github.com/equinor/radix-cost-allocation-api/models/radix_api"
	application "github.com/equinor/radix-cost-allocation-api/models/radix_api/generated_client/client/application"
	platform "github.com/equinor/radix-cost-allocation-api/models/radix_api/generated_client/client/platform"
	gomock "go.uber.org/mock/gomock"
)

// MockRadixAPIClient is a mock of RadixAPIClient interface.
type MockRadixAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockRadixAPIClientMockRecorder
}

// MockRadixAPIClientMockRecorder is the mock recorder for MockRadixAPIClient.
type MockRadixAPIClientMockRecorder struct {
	mock *MockRadixAPIClient
}

// NewMockRadixAPIClient creates a new mock instance.
func NewMockRadixAPIClient(ctrl *gomock.Controller) *MockRadixAPIClient {
	mock := &MockRadixAPIClient{ctrl: ctrl}
	mock.recorder = &MockRadixAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadixAPIClient) EXPECT() *MockRadixAPIClientMockRecorder {
	return m.recorder
}

// GetRadixApplicationDetails mocks base method.
func (m *MockRadixAPIClient) GetRadixApplicationDetails(appParams *application.GetApplicationParams, token string) (*radix_api.RadixApplicationDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixApplicationDetails", appParams, token)
	ret0, _ := ret[0].(*radix_api.RadixApplicationDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRadixApplicationDetails indicates an expected call of GetRadixApplicationDetails.
func (mr *MockRadixAPIClientMockRecorder) GetRadixApplicationDetails(appParams, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixApplicationDetails", reflect.TypeOf((*MockRadixAPIClient)(nil).GetRadixApplicationDetails), appParams, token)
}

// ShowRadixApplications mocks base method.
func (m *MockRadixAPIClient) ShowRadixApplications(appParams *platform.ShowApplicationsParams, token string) (map[string]*radix_api.RadixApplicationDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowRadixApplications", appParams, token)
	ret0, _ := ret[0].(map[string]*radix_api.RadixApplicationDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowRadixApplications indicates an expected call of ShowRadixApplications.
func (mr *MockRadixAPIClientMockRecorder) ShowRadixApplications(appParams, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowRadixApplications", reflect.TypeOf((*MockRadixAPIClient)(nil).ShowRadixApplications), appParams, token)
}
